services:

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./nginx_html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_sites_enabled:/etc/nginx/sites-enabled
    ports:
      - "80:80"
